name = "__WORKER_NAME__"
main = "dist/worker.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "kv"
id = "__KV_ID__"

[env.production]
name = "__WORKER_NAME__"
account_id = "__ACCOUNT_ID__"
zone_id = "__ZONE_ID__"

[[env.production.kv_namespaces]]
binding = "kv"
id = "__KV_ID__"

[observability.logs]
enabled = true