name = "__WORKER_NAME__"
main = "dist/worker.js"
compatibility_date = "2025-09-16"
upload_source_maps = false
minify = false
no_bundle = true

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "kv"
id = "__KV_ID__"

[env.production]
name = "__WORKER_NAME__"
account_id = "__ACCOUNT_ID__"

[[env.production.kv_namespaces]]
binding = "kv"
id = "__KV_ID__"

[observability.logs]
enabled = true
